# docker-compose.yml
version: '3'
services:
  judgenode:
    build: 
      context: .
      dockerfile: Dockerfile
    image: zihuiliang/judgenode:latest
    ports:
      - "8080:8080"
    storage_opt:
      size: 10G
    mem_limit: 2G
    cpus: 2

