url = "127.0.0.1"
port = "8080"
test_threads = 1
actix_workers = 1
max_json_limit = "512MB"
max_time_limit = "10s"
max_memory_limit = "1GB"
max_per_test_data_limit = "64MB"
max_code_limit = "16KB"
max_db_limit = "5GB"
output_limit = "64MB"
license = "12345678"
tested_user_name = "emjudge-judgenode-tested"
eval_or_interactor_user_name = "emjudge-judgenode-eval"
test_data_db_path = "test_data_db.sqlite3"

[compile_and_exe.languages.COBOL]
exe_files = ["main"]
raw_code = "main.cob"
compile_command = """
cobc -free -x main.cob -o main"""
exe_command = """
./main"""

[compile_and_exe.languages.Scala]
exe_files = ["Main.class", "Main$.class"]
compile_command = """
scalac -d . Main.scala"""
exe_command = """
scala -J-Xmx4g -J-Xss256m Main"""
raw_code = "Main.scala"

[compile_and_exe.languages.Javascript]
exe_files = ["main.js"]
exe_command = "node main.js"

[compile_and_exe.languages.Go]
exe_files = ["main"]
raw_code = "main.go"
exe_command = """
./main"""
compile_command = """
go build -o main main.go"""

[compile_and_exe.languages.Swift]
exe_command = """
./main"""
exe_files = ["main"]
raw_code = "main.swift"
compile_command = """
swiftc main.swift -o main"""

[compile_and_exe.languages.Ruby]
exe_command = """
ruby main.rb"""
exe_files = ["main.rb"]

[compile_and_exe.languages.OCaml]
raw_code = "main.ml"
compile_command = """
ocamlc main.ml -o main"""
exe_files = ["main"]
exe_command = """
./main"""

[compile_and_exe.languages.Rust]
raw_code = "main.rs"
exe_files = ["main"]
exe_command = """
./main"""
compile_command = """
rustc main.rs -o main"""

[compile_and_exe.languages.Julia]
exe_command = """
julia --startup-file=no main.jl"""
exe_files = ["main.jl"]

[compile_and_exe.languages.Smalltalk]
exe_command = """
gst main.st"""
exe_files = ["main.st"]

[compile_and_exe.languages."C#"]
exe_command = """
./main"""
raw_code = "main.cs"
exe_files = ["main"]
compile_command = """
mcs -out:main main.cs"""

[compile_and_exe.languages.PHP]
exe_files = ["main.php"]
exe_command = """
php main.php"""

[compile_and_exe.languages.Java]
exe_files = ["Main.class"]
compile_command = """
javac Main.java"""
exe_command = """
java -Xmx4g -Xss256m Main"""
raw_code = "Main.java"

[compile_and_exe.languages."C++"]
exe_command = """./main"""
exe_files = ["main"]
compile_command = """
g++ main.cpp -o main -static -O2 -lm -w -Wno-unused-result -std=c++2a"""
raw_code = "main.cpp"

[compile_and_exe.languages.Tcl]
exe_files = ["main.tcl"]
exe_command = """
./main.tcl"""

[compile_and_exe.languages."Pypy 2"]
exe_command = """
pypy2 main.py2"""
exe_files = ["main.py2"]

[compile_and_exe.languages.Lua]
exe_files = ["main.lua"]
exe_command = """
lua main.lua"""

[compile_and_exe.languages."Common LISP"]
exe_files = ["main.lisp"]
exe_command = """
sbcl --script main.lisp"""

[compile_and_exe.languages.C]
compile_command = """
gcc main.c -o main -O2 -lm -w -Wno-unused-result"""
exe_command = """
./main"""
raw_code = "main.c"
exe_files = ["main"]

[compile_and_exe.languages."Python 2"]
exe_command = """
python2 main.py2"""
exe_files = ["main.py2"]

[compile_and_exe.languages.Octave]
exe_command = """
octave --no-gui --no-window-system main.m"""
exe_files = ["main.m"]

[compile_and_exe.languages."Python 3"]
exe_files = ["main.py3"]
exe_command = """
python3 main.py3"""

[compile_and_exe.languages.Fortran]
compile_command = """
gfortran -o main main.f90 -ffree-form"""
exe_files = ["main"]
exe_command = """
./main"""
raw_code = "main.f90"

[compile_and_exe.languages.Perl]
exe_command = """
./main.pl"""
exe_files = ["main.pl"]

[compile_and_exe.languages."Pypy 3"]
exe_files = ["main.py3"]
exe_command = """
pypy3 main.py3"""

[compile_and_exe.languages.Ada]
compile_command = """
gnatmake -o main main.adb"""
exe_files = ["main"]
raw_code = "main.adb"
exe_command = """
./main"""

[compile_and_exe.languages.Kotlin]
raw_code = "Main.kt"
exe_files = ["Main.jar"]
compile_command = """
kotlinc Main.kt -include-runtime -d Main.jar"""
exe_command = """
kotlin Main.jar"""